import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from data_loader import parse_gmd_file, load_ground_truth
from batch_estimator import run_batch_least_squares, get_sigma_bounds
import os
# =============================================================================
# MAIN ORBIT DETERMINATION WORKFLOW
# =============================================================================

def main():
    # 1. LOAD DATA
    # Load noisy observations generated by GMAT (.gmd)
    # Load ground truth states for final error verification (.csv)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    obs_path = os.path.join(project_root, 'data', 'satellite_observations.gmd')
    truth_path = os.path.join(project_root, 'data', 'ground_truth.csv')
    
    print("--- Project 2: Batch Orbit Determination ---")
    print(f"Looking for data in: {os.path.join(project_root, 'data')}")
    obs_df = parse_gmd_file(obs_path)
    truth_df = load_ground_truth(truth_path)
    
    # 2. DEFINE INITIAL GUESS (Perturbed State)
    # To demonstrate that the Batch algorithm works, we take the "True" state
    # at t0 and add a significant error (e.g., 5 km in position, 5 m/s in velocity).
    # If the algorithm is correct, it will "pull" this dirty guess back to the truth.
    
    t0_mjd = obs_df['Time_MJD'].iloc[0]
    
    # Extract the true state from GMAT at the start time
    # Note: Column names in your truth.csv are X, Y, Z, VX, VY, VZ
    x_true = np.array([
        truth_df['X'].iloc[0], truth_df['Y'].iloc[0], truth_df['Z'].iloc[0],
        truth_df['VX'].iloc[0], truth_df['VY'].iloc[0], truth_df['VZ'].iloc[0]
    ])
    
    # Create the "Dirty" Initial Guess
    pos_error = np.array([2.0, -3.0, 1.5]) # km
    vel_error = np.array([0.005, -0.002, 0.001]) # km/s (5, -2, 1 m/s)
    
    x_initial_guess = x_true + np.concatenate([pos_error, vel_error])
    
    # 3. RUN BATCH LEAST SQUARES
    # This executes the iterative loop from batch_estimator.py
    x_estimated, p_matrix, final_residuals = run_batch_least_squares(
        obs_df, 
        x_initial_guess, 
        max_iterations=8, 
        convergence_tol=1e-7
    )
    
    if x_estimated is None:
        print("Estimation failed.")
        return

    # 4. ERROR ANALYSIS
    # Compare the estimated state at t0 with the true state at t0
    error = x_estimated - x_true
    pos_err_norm = np.linalg.norm(error[0:3]) * 1000.0 # Convert to meters
    vel_err_norm = np.linalg.norm(error[3:6]) * 1000.0 # Convert to m/s
    
    # Extract 3-sigma uncertainties from the Covariance Matrix
    sigmas = get_sigma_bounds(p_matrix)
    pos_3sigma = np.linalg.norm(sigmas['pos_sigma']) * 3.0 * 1000.0 # meters
    
    print("\n--- FINAL ESTIMATION RESULTS ---")
    print(f"Position Error: {pos_err_norm:.3f} meters")
    print(f"Velocity Error: {vel_err_norm:.4f} meters/second")
    print(f"Estimated 3rd-Sigma Position Uncertainty: {pos_3sigma:.3f} meters")
    
    # 5. VISUALIZATION
    # Plotting Post-Fit Residuals (They should look like zero-mean white noise)
    plt.figure(figsize=(10, 6))
    plt.plot(final_residuals, 'o', markersize=3, alpha=0.6, color='blue')
    plt.axhline(0, color='red', linestyle='--')
    plt.title('Post-Fit Residuals (Range & RangeRate Combination)')
    plt.xlabel('Observation Index')
    plt.ylabel('Residual Value [km or km/s]')
    plt.grid(True, alpha=0.3)
    plt.show()

    # Success message
    print("\nProject 2 completed successfully. Check the residual plots for convergence.")

if __name__ == "__main__":
    main()